### ISSUE TITLE
Github Updater not working?

### ISSUE THREAD

**Issue by jatacid** [slfrsn/Divi-Cinematic#4]
Hi slfrsn - I came across your implementation of github updater and it's really simple but doesn't seem to be working for me.  Is this code current or does it not actually work?
Cheers

**Comment by slfrsn** [comment]
The code is current and it's working in production for two clients. I'll need to know more about your setup to help. Just to get the simple stuff out of the way...
1. Have you updated the `$user` and `$repo` variables to reflect your repository?
2. Have you created a GitHub release that matches the new version number in your theme's `styles.css`?

The function I wrote checks your repository for the latest release, grabs the version number, and matches it against the version currently installed (using the theme's current version number in `styles.css`). To make sure this works, every time you commit an update to your theme you'll need to [create a release](https://help.github.com/articles/creating-releases/) with a version number that matches what you've entered into your stylesheet.

For example, if I just committed version 1.2.3 of my theme, I'd need to create a release with 1.2.3 (or any variation of semantic versioning) as the version number. The final step is to then upload a zip file of the theme with the same name as the theme folder (in my case, the theme's folder name is divi-cinematic so I upload `divi-cinematic.zip`). It's important to use the same name for the zip file, otherwise if you append a version number to the file it won't overwrite the theme directory and it makes a huge mess in your themes folder.

I hope that helps. I'm here if you need help or have any further questions :)

**Comment by jatacid** [comment]
Thanks.
It's a child theme and updated user and repo variables as well as the styles.css to match Author, Theme urls and version number.

I was not aware of needing to create a release but I'm unclear about your final step "upload a zip file"

I was under the impression that github automatically combines a repo into a zip for you - why would I need to upload a .zip to my repository? 
Or are you talking about my wordpress wp-content/themes folder where the plugin will be installed?

Cheers!

Jat

**Comment by slfrsn** [comment]
Yes, GitHub creates a zipball for you but the name of the zip reflects the commit it was created from (for example the name of my latest zipball is `slfrsn-Divi-Cinematic-1.5.3-0-g7fd2e66.zip`. The problem is that WordPress will install the update but won't delete the previous version because the folder names are different. It's important to use the same file name for every update so WordPress can properly remove the previous version and prevent duplicates in your theme directory.

It might be possible to assign custom names to zipballs using the releases API or a webhook, but I haven't looked into it.

**Comment by jatacid** [comment]
Interesting thanks!
